// Generated by scripts/services/gen_services.ts from
// scripts/services/endpoints.json.  Edit the manifest (and re-run the
// generator) to change the wrapped method list.  Hand edits to this
// file are preserved as long as the corresponding entry stays in the
// hand-written SKIP_LIST.
import { type BaseClient } from "../../core/mod.js";
import type { ProtocolKey } from "../../thrift/mod.js";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.js";
import type * as LINETypes from "@vyline/line-types";

export class PremiumFontService implements BaseService {
  client: BaseClient;
  protocolType: ProtocolKey = 4;
  requestPath = "/EXT/talk/asset-meta-server/thrift/fontService";
  errorName = "PremiumFontServiceError";
  constructor(client: BaseClient) {
    this.client = client;
  }

  async getAccessToken(
    ...param: Parameters<typeof LINEStruct.getAccessToken_args>
  ): Promise<LINETypes.getAccessToken_result["success"]> {
    return await this.client.request.request(
      LINEStruct.getAccessToken_args(...param),
      "getAccessToken",
      this.protocolType,
      true,
      this.requestPath,
    );
  }

  async getFontMetas(
    ...param: Parameters<typeof LINEStruct.getFontMetas_args>
  ): Promise<LINETypes.getFontMetas_result["success"]> {
    return await this.client.request.request(
      LINEStruct.getFontMetas_args(...param),
      "getFontMetas",
      this.protocolType,
      true,
      this.requestPath,
    );
  }
}
