import { type BaseClient } from "../../core/mod.js";
import type { ProtocolKey } from "../../thrift/mod.js";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.js";
import type * as LINETypes from "@vyline/line-types";
export declare class ShopService implements BaseService {
    client: BaseClient;
    protocolType: ProtocolKey;
    requestPath: string;
    errorName: string;
    constructor(client: BaseClient);
    getProductsByAuthor(...param: Parameters<typeof LINEStruct.getProductsByAuthor_args>): Promise<LINETypes.getProductsByAuthor_result["success"]>;
    getStudentInformation(...param: Parameters<typeof LINEStruct.getStudentInformation_args>): Promise<LINETypes.getStudentInformation_result["success"]>;
    canReceivePresent(...param: Parameters<typeof LINEStruct.canReceivePresent_args>): Promise<void>;
    getOwnedProductSummaries(...param: Parameters<typeof LINEStruct.getOwnedProductSummaries_args>): Promise<LINETypes.getOwnedProductSummaries_result["success"]>;
    getProductV2(...param: Parameters<typeof LINEStruct.getProductV2_args>): Promise<LINETypes.getProductV2_result["success"]>;
    getProductByVersion(...param: Parameters<typeof LINEStruct.getProductByVersion_args>): Promise<LINETypes.getProductByVersion_result["success"]>;
    placePurchaseOrderForFreeProduct(...param: Parameters<typeof LINEStruct.placePurchaseOrderForFreeProduct_args>): Promise<LINETypes.placePurchaseOrderForFreeProduct_result["success"]>;
    placePurchaseOrderWithLineCoin(...param: Parameters<typeof LINEStruct.placePurchaseOrderWithLineCoin_args>): Promise<LINETypes.placePurchaseOrderWithLineCoin_result["success"]>;
    getPurchasedProducts(...param: Parameters<typeof LINEStruct.getPurchasedProducts_args>): Promise<LINETypes.getPurchasedProducts_result["success"]>;
    getReceivedPresents(...param: Parameters<typeof LINEStruct.getReceivedPresents_args>): Promise<LINETypes.getReceivedPresents_result["success"]>;
    getSentPresents(...param: Parameters<typeof LINEStruct.getSentPresents_args>): Promise<LINETypes.getSentPresents_result["success"]>;
    notifyProductEvent(...param: Parameters<typeof LINEStruct.notifyProductEvent_args>): Promise<void>;
    getProductValidationScheme(...param: Parameters<typeof LINEStruct.getProductValidationScheme_args>): Promise<LINETypes.getProductValidationScheme_result["success"]>;
    validateProduct(...param: Parameters<typeof LINEStruct.validateProduct_args>): Promise<LINETypes.validateProduct_result["success"]>;
    getRecommendationList(...param: Parameters<typeof LINEStruct.getRecommendationList_args>): Promise<LINETypes.getRecommendationList_result["success"]>;
    getResourceFile(...param: Parameters<typeof LINEStruct.getResourceFile_args>): Promise<LINETypes.getResourceFile_result["success"]>;
    getAutoSuggestionShowcase(...param: Parameters<typeof LINEStruct.getAutoSuggestionShowcase_args>): Promise<LINETypes.getAutoSuggestionShowcase_result["success"]>;
    getSubscriptionStatus(...param: Parameters<typeof LINEStruct.getSubscriptionStatus_args>): Promise<LINETypes.getSubscriptionStatus_result["success"]>;
    getSuggestResourcesV2(...param: Parameters<typeof LINEStruct.getSuggestResourcesV2_args>): Promise<LINETypes.getSuggestResourcesV2_result["success"]>;
    reserveCoinPurchase(...param: Parameters<typeof LINEStruct.reserveCoinPurchase_args>): Promise<LINETypes.reserveCoinPurchase_result["success"]>;
    getCoinUseAndRefundHistory(...param: Parameters<typeof LINEStruct.getCoinUseAndRefundHistory_args>): Promise<LINETypes.getCoinUseAndRefundHistory_result["success"]>;
    getCoinProducts(...param: Parameters<typeof LINEStruct.getCoinProducts_args>): Promise<LINETypes.getCoinProducts_result["success"]>;
    getCoinPurchaseHistory(...param: Parameters<typeof LINEStruct.getCoinPurchaseHistory_args>): Promise<LINETypes.getCoinPurchaseHistory_result["success"]>;
    canCreateCombinationSticker(...param: Parameters<typeof LINEStruct.canCreateCombinationSticker_args>): Promise<LINETypes.canCreateCombinationSticker_result["success"]>;
    createCombinationSticker(...param: Parameters<typeof LINEStruct.createCombinationSticker_args>): Promise<LINETypes.createCombinationSticker_result["success"]>;
    isStickerAvailableForCombinationSticker(...param: Parameters<typeof LINEStruct.isStickerAvailableForCombinationSticker_args>): Promise<LINETypes.isStickerAvailableForCombinationSticker_result["success"]>;
    shouldShowWelcomeStickerBanner(...param: Parameters<typeof LINEStruct.shouldShowWelcomeStickerBanner_args>): Promise<LINETypes.shouldShowWelcomeStickerBanner_result["success"]>;
    stopBundleSubscription(...param: Parameters<typeof LINEStruct.stopBundleSubscription_args>): Promise<LINETypes.stopBundleSubscription_result["success"]>;
    getProductLatestVersionForUser(...param: Parameters<typeof LINEStruct.getProductLatestVersionForUser_args>): Promise<LINETypes.getProductLatestVersionForUser_result["success"]>;
    getMusicSubscriptionStatus(...param: Parameters<typeof LINEStruct.getMusicSubscriptionStatus_args>): Promise<LINETypes.getMusicSubscriptionStatus_result["success"]>;
    addThemeToSubscriptionSlot(...param: Parameters<typeof LINEStruct.addThemeToSubscriptionSlot_args>): Promise<LINETypes.addThemeToSubscriptionSlot_result["success"]>;
}
