// Generated by scripts/services/gen_services.ts from
// scripts/services/endpoints.json.  Edit the manifest (and re-run the
// generator) to change the wrapped method list.  Hand edits to this
// file are preserved as long as the corresponding entry stays in the
// hand-written SKIP_LIST.
import { type BaseClient } from "../../core/mod.js";
import type { ProtocolKey } from "../../thrift/mod.js";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.js";
import type * as LINETypes from "@vyline/line-types";

export class BotExternalService implements BaseService {
  client: BaseClient;
  protocolType: ProtocolKey = 4;
  requestPath = "/BOTE";
  errorName = "BotExternalServiceError";
  constructor(client: BaseClient) {
    this.client = client;
  }

  async notifyOATalkroomEvents(
    ...param: Parameters<typeof LINEStruct.notifyOATalkroomEvents_args>
  ): Promise<LINETypes.notifyOATalkroomEvents_result["success"]> {
    return await this.client.request.request(
      LINEStruct.notifyOATalkroomEvents_args(...param),
      "notifyOATalkroomEvents",
      this.protocolType,
      true,
      this.requestPath,
    );
  }

  async notifyChatAdEntry(
    ...param: Parameters<typeof LINEStruct.notifyChatAdEntry_args>
  ): Promise<LINETypes.notifyChatAdEntry_result["success"]> {
    return await this.client.request.request(
      LINEStruct.notifyChatAdEntry_args(...param),
      "notifyChatAdEntry",
      this.protocolType,
      true,
      this.requestPath,
    );
  }
}
