// Generated by scripts/services/gen_services.ts from
// scripts/services/endpoints.json.  Edit the manifest (and re-run the
// generator) to change the wrapped method list.  Hand edits to this
// file are preserved as long as the corresponding entry stays in the
// hand-written SKIP_LIST.
import { type BaseClient } from "../../core/mod.js";
import type { ProtocolKey } from "../../thrift/mod.js";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.js";
import type * as LINETypes from "@vyline/line-types";

export class PrimarySeamlessLoginService implements BaseService {
  client: BaseClient;
  protocolType: ProtocolKey = 4;
  requestPath = "/EXT/auth/feature-user/api/secondary/login/seamless";
  errorName = "PrimarySeamlessLoginServiceError";
  constructor(client: BaseClient) {
    this.client = client;
  }

  async permitLogin(
    ...param: Parameters<typeof LINEStruct.permitLogin_args>
  ): Promise<LINETypes.permitLogin_result["success"]> {
    return await this.client.request.request(
      LINEStruct.permitLogin_args(...param),
      "permitLogin",
      this.protocolType,
      true,
      this.requestPath,
    );
  }
}
